--- #YAML:1.0
name:               Net-DAV-Server
version:            1.300_02
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::SHA1:         0
    Encode:               0
    File::Find::Rule::Filesys::Virtual:  0
    File::Slurp:          0
    HTTP::Date:           0
    HTTP::Headers:        0
    HTTP::Request:        0
    HTTP::Response:       0
    Test::More:           0
    URI:                  0
    URI::Escape:          0
    XML::LibXML:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
